Updated to Kafka 10
redBorder/cep pull request #10
Opened 2016-10-10 17:27 UTC by pablocasares

The Kafka API has been updated to Kafka 10 and now the CEP supports keyed messages at the Kafka input/output. The CEP will produce the message to the output topic with the same key which they had at the input. If the message is consumed without key it will be produced to the partition 0. 

For example: 
* Input [key, message]: keyA, {"value":0,"type":"rx_pkts_tunnel"}
* Rule: 
```{
  "id": "rule1",
  "input": ["inputTopic"],
  "output": { "outputtopic": "output_topic" },
  "executionPlan": "from inputTopic select value, type insert into outputtopic"
}```

will produce as output:

```keyA, {"value":0,"type":"rx_pkts_tunnel"}```

and: 
* Input [key, message]:  null, {"value":0,"type":"rx_pkts_tunnel"}
* Same rule as above

will produce as output (at partition 0):
```null, {"value":0,"type":"rx_pkts_tunnel"}```

2016-10-11 07:23 UTC, andresgomezfrr requested changes
Add some integration test using EmbeddedSingleNodeKafkaCluster class.

2016-10-11 07:23 UTC, andresgomezfrr commented on pom.xml
>          <dependency>
I think that you can use

```xml
<dependency>
    <groupId>org.apache.kafka</groupId>
    <artifactId>kafka-clients</artifactId>
    <version>0.10.0.1</version>
</dependency>
```

2016-10-11 07:23 UTC, andresgomezfrr commented on src/main/java/net/redborder/cep/sinks/kafka/KafkaSink.java
> +        props.put("bootstrap.servers", ConfigData.getKafkaBrokers());
You can use the ProducerConfigs class to define the properties.

2016-10-11 07:23 UTC, andresgomezfrr commented on src/main/java/net/redborder/cep/sinks/kafka/KafkaSink.java
> +            producer.flush();
You don't need to do a flush each send. You need to do a flush when shutdown the system.

2016-10-11 07:23 UTC, andresgomezfrr commented on src/main/java/net/redborder/cep/sinks/kafka/SimplePartitioner.java
> +        return (key == null) ? 0 : Math.abs(key.hashCode() % cluster.partitionCountForTopic(topic));
Better thant hashCode you can use murmur2 

```java
import org.apache.kafka.common.utils.Utils;

Utils.abs(Utils.murmur2(key.getBytes())) % numPartitions
```

2016-10-11 07:23 UTC, andresgomezfrr commented on src/main/java/net/redborder/cep/sinks/syslog/SyslogSink.java
> +        if (message.containsKey("__KEY")) {
Create a utils class to define a string constant to __KEY

2016-10-11 07:23 UTC, andresgomezfrr commented on src/main/java/net/redborder/cep/sources/kafka/KafkaSource.java
> +        for (Consumer consumer : consumers) {
I Think that you don't need this if you do 

``` java
executor.shutdown(); 
```

2016-10-18 13:33 UTC, pablocasares commented
The changes requested have been finished.

2016-10-18 14:08 UTC, andresgomezfrr approved these changes

2016-10-18 14:09 UTC, closed without merging